# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.name = "centos_7_docker-compose"
  end

  config.vm.network :forwarded_port, host: 2231, guest: 22
  config.vm.network "private_network", ip: "192.168.33.21"

  # copy config files into VM
  config.vm.provision "file", source: "config/resolv.conf", destination: "config/resolv.conf"
  config.vm.provision "file", source: "config/smb.conf", destination: "config/smb.conf"

  # Run scripts for all VMs  
  config.vm.provision :shell, path: 'scripts/common.sh'
  config.vm.provision :shell, path: 'scripts/create_linux_user.sh'
  config.vm.provision :shell, path: 'scripts/set_samba.sh'
  config.vm.provision :shell, path: 'scripts/set_docker_compose.sh'
  config.vm.provision :shell, path: 'scripts/clean_up.sh'
end
